server {
    listen 80;
    server_name deployment-demo.com;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;
    server_name deployment-demo.com;

    ssl_certificate /etc/letsencrypt/live/deployment-demo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/deployment-demo.com/privkey.pem;


    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}