services:
  db:
    image: postgres:15
    container_name: postgres-container
    env_file:
      - .env
  backend:
    build: ./server
    container_name: django-container
    command: sh -c "gunicorn task_proj.wsgi --bind 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db

  # frontend:
  #   build: ./client
  #   container_name: nginx-container
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./client/dist:/usr/share/nginx/html
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - backend